name: Export Issues to Excel

on:
  workflow_dispatch:

jobs:
  export-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install axios xlsx
      - name: Export issues to Excel
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const axios = require("axios");
          const XLSX = require("xlsx");
          const token = process.env.TOKEN;
          const headers = {
            "Authorization": `Token ${token}`
          };
          const repoName = "nodeaffinity";
          const repoOwner = "saquibkhan";
          axios.get(`https://api.github.com/repos/${repoOwner}/${repoName}/issues`, { headers })
            .then(response => {
              const workbook = XLSX.utils.json_to_sheet(response.data);
              XLSX.writeFile(XLSX.utils.book_new([workbook]), "issues.xlsx");
